spring:
  application:
    name: codo
  data:
    redis:
      host: localhost
      port: 6379
      timeout: 60000
  datasource:
    url: jdbc:postgresql://localhost:5432/codo_db
    username: codo_rw
    password: a123456
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

app:
  base-url: http://localhost:8080

maileroo:
  api:
    token: ${MAILEROO_API_TOKEN:123456}
  from:
    email: ${MAILEROO_FROM_EMAIL:noreply@test.org}
  mock:
    enabled: false